!INCLUDE nmake.opt

.cpp.obj:
	$(CXX) -c $<

OBJ	= \
	jpg2svs.obj \
	jpgcachesupport.obj \
       	imagesupport.obj \
       	jpgsupport.obj \
       	tiffsupport.obj \
       	composite.obj \
       	console-mswin.obj

all: 	jpg2svs.exe

jpg2svs.exe: $(OBJ)
	$(LD) /debug /out:jpg2svs.exe /SUBSYSTEM:console $(OBJ) $(JPEG_LIB) $(TIFF_LIB) $(OPENCV_LIB) 



clean:
	-del *.obj
	-del *.exe
	-del *.pdb
